# Generated by Django 4.2.7 on 2025-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicom', '0003_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('services', 'Services'), ('goods', 'Goods')], max_length=100, null=True),
        ),
    ]
