# Generated by Django 4.2.7 on 2025-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicom', '0004_alter_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-image'),
        ),
    ]
