# Generated by Django 4.2.7 on 2025-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicom', '0005_profile_bio_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_details',
            field=models.TextField(help_text='Enter the details of how issue was resolved', null=True),
        ),
    ]
