# Generated by Django 4.2.7 on 2025-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicom', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolved_details',
            field=models.TextField(blank=True, help_text='Enter the details of how issue was resolved', null=True),
        ),
    ]
