# Generated by Django 4.2.7 on 2025-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicom', '0008_alter_complaint_resolved_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mat_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
